#!/bin/bash
if test ! "$(which python)"; then
  echo "Please install python first"
  exit 1
fi

if test ! "$(which yay)"; then
  echo "Please install yay first"
  exit 1
fi

if test ! "$(which ansible)"; then
  echo "Please install ansible first"
  exit 1
fi

if test ! -f /usr/share/ansible/plugins/modules/yay; then
  echo "Execute the following to install ansible-yay module"
  cat <<-EOF
			# curl -fLo /usr/share/ansible/plugins/modules/yay --create-dirs \
					https://raw.githubusercontent.com/mnussbaum/ansible-yay/master/yay
			# chmod -R 755 /usr/share/ansible/plugins
			EOF
fi

python --version
ansible --version
ansible-playbook -K main.yml
