#!/bin/bash
if test ! "$(which yay)"; then
  echo "Please install yay first"
  exit 1
fi

if test ! "$(which ansible)"; then
  echo "Please install ansible first"
  exit 1
fi

if [ ! -f /usr/share/ansible/plugins/modules/yay ]; then
  wget -O /usr/share/ansible/plugins/modules/yay https://raw.githubusercontent.com/mnussbaum/ansible-yay/master/yay
fi

python --version
ansible --version
ansible-playbook -K main.yml

