- name: Install audio daemon
  become: yes
  block:
    - name: install
      pacman: name=mpd
    - name: enable
      systemd: name=mpd enabled=yes state=started

- name: Install audio tools
  become: yes
  pacman:
    name:
      - alsa-utils
      - pulseaudio
      - pulseaudio-alsa
      - pavucontrol
